import type { Metadata } from "next";
import {geistSans,geistMono} from '@/lib/fonts'
import "./globals.css";

export const metadata: Metadata = {
  title: "JuriDesk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
